name: validate-build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.10.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v7
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemp.exportVariable("ID_TOKEN", id_token);
      - name: Read env
        shell: bash
        run: echo ${{ env.ID_TOKEN }}